### PR TITLE
changing names in output tree

### PR DESCRIPTION
**Pull request by marianstahl**
I had some problems processing the output tree with RDataFrame because of the leading underscore and hashtags/tildes. 

Feel free to close or merge this. I understand that changing naming conventions that late might cause crashes in scripts of other users

### CODE REVIEW

**Comment by tevans1260** [comment]
I entirely agree that the names here are quite annoying. Unfortunately as you say, it's difficult to fix without breaking other user code (indeed, these names are a hangover from when it was MINT, which is when I probably should have fixed this). The best thing would be to therefore add an additional flag / NamedParameter (off by default) that switches to more modern names.

**Comment by marianstahl** [comment]
That sounds like a reasonable compromise. I don't have time for it today, and I'm only back next Thursday, but it's on my todo list

**Comment by marianstahl** [comment]
Hi @tevans1260 ! I finally had some time to look at the pull request again. Let me know if anything is missing (documentation etc) or could be improved. Sorry for all the unrelated whitespace changes

**Comment by tevans1260** [comment]
Merged. Cool - this is very nice. I'll probably switch my files to use this naming scheme at some point. 

I wonder if it would be a little nicer to use an enum to store which output format to use - in this way we future proof for if for example, we have other branch formats to use (which there already is to some extent in the QcGenerator to match the format of CLEO-c data)

**Comment by marianstahl** [comment]
Thanks! Having an enum would be nice. I'm not fully sure how it would work in detail from the options to the parsed name. Probably the parsing could be stored in some std::function

**Comment by tevans1260** [comment]
See the arcane macro nonsense in enum.h for this. The already-use case of this is to have literals (fix, free, etc. ) rather than the mysterious (0,1,2) fit flags in options file(s). For taking the options and giving the names, an if/else block would work, but it might be possible to do something more fun...

**Pull request merged**
